apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: amt6nboky-go 
  janus-idp.io/tekton: amt6nboky-go
  backstage.io/kubernetes-id: amt6nboky-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: amt6nboky-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  