apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: amt6nboky-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: amt6nboky-go 
  name: amt6nboky-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: amt6nboky-go 
